#!/usr/bin/env bash
# cognitive-complexity-ts -- alternative tool, branch JS_V22_ROLLUP_YARN_MICRO (Node 22).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/tools/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "cognitive-complexity-ts" "cognitive-complexity-ts" "cognitive-complexity-ts@0.8.2"

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
cognitive-complexity-ts packages
rc=$?
accept_findings "cognitive-complexity-ts" "$rc" "reports/cognitive-complexity-ts.json"
exit $?
