#!/usr/bin/env bash
# OpenGrep -- alternative tool, branch JS_V24_ESBUILD_BUN_MICRO (Node 24).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_binary "opengrep" "opengrep"

cd "$ROOT"
FINDINGS_EXIT=1
opengrep scan --json -o reports/opengrep.json packages
rc=$?
accept_findings "opengrep" "$rc" "reports/opengrep.json"
exit $?
