#!/usr/bin/env bash
# nyc + mocha -- primary tool, branch JS_V16_RSPACK_PNPM_MICRO (Node 16).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "nyc" "nyc" "nyc@15.1.0"
require_smoke "nyc" "nyc@15.1.0" node_modules/.bin/nyc --version

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
nyc --reporter=json --reporter=cobertura npm test
rc=$?
accept_findings "nyc" "$rc" "coverage/coverage-final.json"
exit $?
