#!/usr/bin/env bash
# Trivy -- alternative tool, branch JS_V14_VITE_PNPM_MONO (Node 14).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_binary "trivy" "trivy"

cd "$ROOT"
FINDINGS_EXIT=1
trivy fs --format json -o reports/trivy.json .
rc=$?
accept_findings "trivy" "$rc" "reports/trivy.json"
exit $?
