#!/usr/bin/env python3
"""PyDriller -- primary tool, Code Churn block. Real git-history miner,
not a stub: walks this branch's actual commit log with pydriller and
reports per-file commit counts. Generated by gen_js_corpus.py."""
import json
import os
import sys

try:
    from pydriller import Repository
except ImportError as exc:
    print("STATUS: SKIPPED")
    print("  tool  : pydriller")
    print("  reason: pydriller is not importable in this environment: %s" % exc)
    sys.exit(3)

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

if not os.path.exists(os.path.join(ROOT, ".git")):
    print("STATUS: NOT INSTALLED")
    print("  tool  : pydriller")
    print("  reason: %s is not a git repository, and this tool mines history." % ROOT)
    sys.exit(4)

churn = {}
commits = 0
try:
    for commit in Repository(ROOT).traverse_commits():
        commits += 1
        for f in commit.modified_files:
            path = f.new_path or f.old_path
            if not path:
                continue
            churn[path] = churn.get(path, 0) + 1
except Exception as exc:  # pragma: no cover -- real failure, not masked
    print("STATUS: FAILED")
    print("  tool  : pydriller")
    print("  error : %s" % exc)
    sys.exit(1)

os.makedirs(os.path.join(ROOT, "reports"), exist_ok=True)
with open(os.path.join(ROOT, "reports", "pydriller.json"), "w") as fh:
    json.dump({"commits": commits, "churnByFile": churn}, fh, indent=2)

print("STATUS: RAN")
print("  tool    : pydriller")
print("  commits : %d" % commits)
print("  files   : %d" % len(churn))
sys.exit(0)
