#!/usr/bin/env bash
# diff-cover -- primary tool, branch JS_V24_PARCEL_PNPM_MICRO (Node 24).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/tools/_skip.sh"

mkdir -p "$ROOT/reports"
require_binary "diff-cover" "diff-cover"

cd "$ROOT"
FINDINGS_EXIT=1
diff-cover coverage/cobertura-coverage.xml --json-report reports/diff-cover.json
rc=$?
accept_findings "diff-cover" "$rc" "reports/diff-cover.json"
exit $?
