#!/usr/bin/env bash
# Git-Spark -- alternative tool, branch JS_V24_ROLLUP_YARN_MONO (Node 24).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/tools/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "git-spark" "git-spark" "git-spark@1.3.2"

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
git-spark analyze --format json --output reports/git-spark.json
rc=$?
accept_findings "git-spark" "$rc" "reports/git-spark.json"
exit $?
