#!/usr/bin/env bash
# eslint-plugin-sonarjs -- primary tool, branch JS_V14_RSPACK_NPM_MONO (Node 14).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "sonarjs" "eslint-plugin-sonarjs" "eslint-plugin-sonarjs@4.2.1"

cd "$ROOT"
FINDINGS_EXIT=1
node_modules/.bin/eslint . --no-eslintrc --rulesdir . --parser-options=ecmaVersion:2022 --rule '{"sonarjs/cognitive-complexity": "warn"}' -f json -o reports/sonarjs.json 2>&1 || true
node_modules/.bin/eslint . --rule '{"sonarjs/cognitive-complexity": "warn"}' -f json -o reports/sonarjs.json
rc=$?
accept_findings "sonarjs" "$rc" "reports/sonarjs.json"
exit $?
