#!/usr/bin/env bash
# oxlint -- alternative tool, branch JS_V20_VITE_PNPM_MICRO (Node 20).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "oxlint" "oxlint" "oxlint@1.83.0"
require_smoke "oxlint" "oxlint@1.83.0" node_modules/.bin/oxlint --version

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
oxlint . --format json > reports/oxlint.json
rc=$?
accept_findings "oxlint" "$rc" "reports/oxlint.json"
exit $?
