#!/usr/bin/env bash
# ESLint (eslint-scope) -- primary tool, branch JS_V24_ROLLUP_NPM_MICRO (Node 24).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/tools/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "eslint-scope" "eslint-scope" "eslint-scope@9.1.2"

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
node scripts/dataflow-scope.js packages
rc=$?
accept_findings "eslint-scope" "$rc" "reports/dataflow.json"
exit $?
