#!/usr/bin/env bash
# StrykerJS + Mocha -- primary tool, branch JS_V18_ESBUILD_PNPM_MICRO (Node 18).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "stryker" "@stryker-mutator/core" "@stryker-mutator/core@8.7.1"
require_smoke "stryker" "@stryker-mutator/core@8.7.1" node_modules/.bin/stryker --version

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
stryker run
rc=$?
accept_findings "stryker" "$rc" "reports/mutation.json"
exit $?
