"""Metadata table for the JavaScript-Tools-Invalid corpus: one entry per
tool folder, used to generate each folder's README.md. Mirrors
JavaScript-Tools-Clean's own meta.py, inverted: every "measured" tool here
is engineered and empirically verified to produce a genuine FINDING
(majority-wrong by some concrete, falsifiable metric), not a clean pass.
"""

TOOLS = [
    {
        "tool": "cccc", "package": "ledger", "status": "measured",
        "domain": "A freight-surcharge ledger written in C -- CCCC parses C/C++/Java, not JavaScript (same documented category error as the Clean sibling).",
        "invalid_means": "cccc's own cccc.xml reports a module cyclomatic complexity of 33, more than 3x the threshold of 10.",
        "command": "cccc src/*.c && (parse .cccc/cccc.xml)",
        "notes": "classify_surcharge_cents and weight_tier_code are both deliberately tangled (dense if/else chains and a 12-way switch). cccc groups the whole file into one 'anonymous' module in this version, whose combined McCabe cyclomatic complexity (33) is measured for real and is more than 3x over threshold -- a clear, reproducible FINDING, not asserted.",
    },
    {
        "tool": "CodeQL", "package": "beacon", "status": "not_installed",
        "domain": "A lighthouse beacon flash scheduler with eval(), a shell command built from string concatenation, and a weak PRNG for a security-relevant id.",
        "invalid_means": "A default CodeQL JS/TS query pack would flag the eval(), the child_process concatenation, and the weak randomness -- all three are present and real, but CodeQL itself cannot be measured here (see notes).",
        "command": "codeql database create ... && codeql database analyze ...  (not runnable here -- see notes)",
        "notes": "Same egress constraint as the Clean sibling: the CodeQL CLI and query packs ship as GitHub release assets, and this sandbox's allowlist returns 403 for github.com release downloads. Source only, genuinely insecure by inspection, not measured in this environment.",
    },
    {
        "tool": "debtmap", "package": "harborlog", "status": "measured",
        "domain": "A harbor berth-assignment log with copy-pasted, deeply-nested arrive()/depart() methods and a dead unusedLegacyReport() method.",
        "invalid_means": "debtmap analyze reports a debt density of 472.4 per 1K LOC against a 10.0 threshold -- more than 47x over.",
        "command": "debtmap analyze . --format terminal",
        "notes": "debtmap validate reports '0 files analyzed' unconditionally in this installed version (0.24.1) -- a genuine, content-independent quirk reproduced even against the original Clean-corpus source, not something this fixture caused. debtmap analyze does not have this bug, so it is used as the real measurement: 3 CRITICAL/HIGH findings (arrive, depart, unusedLegacyReport), debt density 472.4 per 1K LOC vs. the 10.0 threshold.",
    },
    {
        "tool": "diff-cover", "package": "tallyframe", "status": "measured",
        "domain": "A scoreboard tally tracker, with a real git history and a feature branch adding allTied/marginOfVictory/rankPlayers, almost entirely untested.",
        "invalid_means": "diff-cover reports 41.7% coverage on the feature branch's diff against main -- 58.3% of the new lines are uncovered.",
        "command": "nyc --reporter=cobertura mocha 'test/**/*.test.js' && diff-cover coverage/cobertura-coverage.xml --compare-branch=main --fail-under=100",
        "notes": "Only allTied() is tested; marginOfVictory() and rankPlayers() are added in the same commit with no covering test at all, so the majority of the diff's new lines (7 of 12) are genuinely uncovered.",
    },
    {
        "tool": "Dolos", "package": "kelpfield", "status": "measured",
        "domain": "An aquarium kelp-growth and water-chemistry tracker split across three files; growth.js is a near-verbatim structural clone of feeding.js (renamed identifiers only).",
        "invalid_means": "Dolos reports a pairwise similarity score of 1.0 (the maximum) between feeding.js and growth.js, far over the 0.3 FINDINGS threshold.",
        "command": "dolos run src/*.js -l javascript",
        "notes": "feeding.js (FeedingLog) and growth.js (GrowthLog) have identical structure, identical control flow, and identical method shapes -- only identifiers differ. Dolos's own fragment matcher reports the maximum similarity score of 1.0.",
    },
    {
        "tool": "ESLint", "package": "orderdesk", "status": "measured",
        "domain": "A cafe order queue with running-total pricing, deliberately riddled with var usage, loose equality, an undefined global reference, and an unused variable.",
        "invalid_means": "eslint reports 8 real errors across all 5 configured rules (no-var, no-unused-vars, eqeqeq x2, no-undef x2, prefer-const).",
        "command": "eslint src/ test/",
        "notes": "Every one of the folder's own 5 configured rules fires at least once -- not a single marginal violation but a genuinely bad file by its own config's standard.",
    },
    {
        "tool": "eslint-plugin-security", "package": "latchbox", "status": "measured",
        "domain": "A combination-lock simulator using eval(), a child_process.exec() built from string concatenation, and an unused variable.",
        "invalid_means": "eslint with plugin:security/recommended reports detect-eval-with-expression and detect-child-process, plus a no-unused-vars error.",
        "command": "eslint src/ test/",
        "notes": "describeState() hands a string straight to eval(), and logAttempt() builds a shell command via string concatenation passed to child_process.exec() -- both are exactly the patterns plugin:security/recommended exists to catch, and both fire for real.",
    },
    {
        "tool": "eslint-plugin-sonarjs", "package": "ticketrail", "status": "measured",
        "domain": "A train ticket queue with a surchargeFor() method whose if/else-if chain returns the same value in every branch, and a priorityLabel() method with a repeated identical condition.",
        "invalid_means": "eslint with plugin:sonarjs/recommended reports no-invariant-returns, no-all-duplicated-branches, and no-identical-conditions -- 3 real findings.",
        "command": "eslint src/ test/",
        "notes": "surchargeFor()'s 4-way if/else-if all return 0, and priorityLabel() repeats the same 'isLoyalty === true' condition twice in the same chain -- both are textbook sonarjs findings, not edge cases.",
    },
    {
        "tool": "Git-Spark", "package": "timberyard", "status": "measured",
        "domain": "A lumber-yard module split across 3 files, with a real 91-commit history from 8 rotating authors, each file rewritten ~30 times with substantial (100+ line) diffs.",
        "invalid_means": "git-spark's console report shows Overall Risk Level: MEDIUM (not LOW), with all 3 files flagged for high churn, many authors, and recent changes.",
        "command": "git-spark -f console",
        "notes": "git-spark's own risk-scoring formula weighs per-file churn, author count, commit count, and recency; this history was engineered (3 files, 30 commits each, 8 distinct authors, dated within the measurement window) specifically to cross its internal risk-score threshold for a non-LOW overall rating -- confirmed by running the real tool, not by asserting the category.",
    },
    {
        "tool": "gutcheck", "package": "meterhouse", "status": "measured",
        "domain": "A tiered utility-meter billing calculator whose billCents() is exercised by two tests that both assert only assert.ok(true), never checking the actual return value.",
        "invalid_means": "gutcheck reports 1 of 2 functions as not fully proven ('unnoticed' in this release's terminology): the test executes billCents but would not fail if its logic were destroyed.",
        "command": "gutcheck .",
        "notes": "This installed gutcheck release (0.10.0) reports non-value-pinning tests as 'unnoticed' rather than the older 'hollow' label the corpus's own clean_means uses, but the substance is identical: billCents' own tests never pin a value, so mutating billCents freely would not be caught. usageBetween (properly asserted) is correctly PROVEN.",
    },
    {
        "tool": "jscpd", "package": "spicecrate", "status": "measured",
        "domain": "A spice-inventory crate and a near-duplicate shelf-placement planner -- addStock/removeStock are copy-pasted almost verbatim between the two files.",
        "invalid_means": "jscpd reports 56.02% duplicated tokens (2 real clones, 41.33% duplicated lines) at --min-lines 5 --min-tokens 30 --threshold 0.",
        "command": "jscpd src/ --min-lines 5 --min-tokens 30 --threshold 0 --reporters console",
        "notes": "A genuine majority of the two files' combined content (by token count) is duplicated logic, not an incidental few-line overlap.",
    },
    {
        "tool": "knip", "package": "petalbook", "status": "measured",
        "domain": "A seasonal flower catalog with an entirely unused file (legacyReport.js), an unused devDependency (left-pad), and an unused export (catalog.js's unusedHelper).",
        "invalid_means": "knip reports 1 unused file, 1 unused devDependency, and 1 unused export -- 3 real findings across all 3 of knip's own categories.",
        "command": "knip",
        "notes": "Every category knip checks (files, dependencies, exports) has at least one genuine, real hit -- not a single-category edge case.",
    },
    {
        "tool": "Lizard", "package": "windmill", "status": "measured",
        "domain": "A windmill power-output estimator with an 8-parameter, 66-line, CCN-26 function, plus a 7-parameter, CCN-10 turbine-state classifier.",
        "invalid_means": "lizard -C 10 -L 60 -a 5 -w flags 2 of the file's 3 functions (66.7%) over threshold -- CCN 26 and CCN 10, both over the -C 10 limit, and the first also over length/param-count limits.",
        "command": "lizard src/ -C 10 -L 60 -a 5 -w",
        "notes": "estimatePowerWatts alone is almost a direct CCN/length/param-count hat-trick failure; classifyTurbineState adds a second genuine over-threshold function, for a clear majority (2/3) of the file's functions flagged.",
    },
    {
        "tool": "Mocha", "package": "librastack", "status": "measured",
        "domain": "A library call-number shelving system with 4 deliberate logic bugs (silent overwrite instead of rejection, wrong missing-entry value, off-by-one count, no-op delete).",
        "invalid_means": "4 of the 5 real tests (80%) fail against the real, deliberately buggy implementation.",
        "command": "mocha 'test/**/*.test.js'",
        "notes": "Every bug is a genuine behavioral defect (not a test-writing mistake), and the test suite correctly catches 4 of them when actually run.",
    },
    {
        "tool": "monocart-coverage-reports", "package": "shelfcount", "status": "measured",
        "domain": "A warehouse shelf item-count tracker with a single, minimal test that only exercises addTo()'s own return value.",
        "invalid_means": "The json-summary report's entry for src/shelfcount.js shows 47.05% line coverage, 40% function coverage, 50% branch coverage -- all majority-uncovered.",
        "command": "mcr node node_modules/.bin/mocha 'test/**/*.test.js' -r v8,json-summary -o coverage-report",
        "notes": "countOn, grandTotal, and isOverCapacity are never directly tested; only 2 of the file's 5 functions ever run under test.",
    },
    {
        "tool": "npm audit", "package": "cratebox", "status": "measured",
        "domain": "A shipping-crate manifest that depends on minimist@0.0.8, a real, old, vulnerable runtime dependency.",
        "invalid_means": "npm audit reports 1 critical-severity prototype-pollution vulnerability (GHSA-vh95-rmgr-6w4m / GHSA-xvch-5gv4-984h) -- the folder's single runtime dependency (1 of 1, 100%) is vulnerable.",
        "command": "npm audit --audit-level=low",
        "notes": "minimist@0.0.8 is a real package version with a real, published, critical CVE -- not a synthetic or hypothetical vulnerability.",
    },
    {
        "tool": "npm ls", "package": "satchel", "status": "measured",
        "domain": "A courier's parcel-satchel route tracker declaring 2 dependencies that cannot resolve: left-pad@999.999.999 (a version that does not exist) and is-odd@0.0.1 (never installed).",
        "invalid_means": "npm ls --all reports both of the folder's 2 declared dependencies (100%) as UNMET DEPENDENCY, exiting with ELSPROBLEMS.",
        "command": "npm ls --all",
        "notes": "Both dependencies the folder declares are genuinely unresolvable, not just one of several -- npm ls's own dependency-tree check fails completely, not partially.",
    },
    {
        "tool": "nyc", "package": "paypocket", "status": "measured",
        "domain": "A payroll calculator whose single test only exercises the holiday-pay branch, leaving the standard-hours and overtime-hours branches entirely untested.",
        "invalid_means": "nyc --check-coverage reports 45.45% statement/line coverage and 25% branch coverage -- 54.55% of statements and 75% of branches are genuinely uncovered.",
        "command": "nyc --check-coverage --lines 100 --branches 100 --functions 100 --statements 100 mocha 'test/**/*.test.js'",
        "notes": "A clear majority of both statements and branches are never executed under test.",
    },
    {
        "tool": "OpenGrep", "package": "gatewatch", "status": "measured",
        "domain": "A gate-access badge controller using Math.random() for a visitor code and a child_process.exec() built from string concatenation.",
        "invalid_means": "semgrep (the same-engine stand-in used in the Clean sibling) reports 2 of the folder's own 3 ruleset findings (67%) against the committed semgrep-rules.yml.",
        "command": "opengrep --config=semgrep-rules.yml --error src/  (opengrep binary unavailable -- see notes; semgrep ran instead)",
        "notes": "The opengrep binary itself remains a GitHub release asset blocked by this sandbox's egress allowlist (same as the Clean sibling), but unlike Clean's clean source, this folder's content genuinely trips the same-engine semgrep stand-in: no-insecure-random-for-tokens and no-child-process-exec-with-concat both fire for real.",
    },
    {
        "tool": "oxlint", "package": "tidewatch", "status": "measured",
        "domain": "A tide-station reading log with an unused variable and a stray debugger statement.",
        "invalid_means": "oxlint reports 2 real findings (no-unused-vars, no-debugger). Both are warning-severity by this tool's own default configuration, so (as with Lizard/knip in the Clean sibling's own verify.py) any non-empty output -- not exit code alone -- is treated as the real signal.",
        "command": "oxlint src/ test/",
        "notes": "oxlint's default rule severities are 'warn', which does not by itself flip the process exit code; the corpus's own verify script follows the same any-output-is-a-finding convention already established for Lizard/knip in the Clean sibling's verify.py, rather than trusting exit code alone.",
    },
    {
        "tool": "pydriller", "package": "chronicle", "status": "measured",
        "domain": "A diary module with a real 4-commit, 3-author git history; driver.py deliberately scopes pydriller's own traversal to commits since a cutoff date that excludes part of that real history.",
        "invalid_means": "pydriller (scoped since 2026-01-04) sees 2 of the repo's 4 real commits (50%) and 2 of its 3 real authors, diverging from plain `git log` on both counts.",
        "command": "python3 driver.py",
        "notes": "The divergence is a real, reproducible consequence of pydriller's own `since` filter being pointed at a date that falls inside the true history, not a fabricated mismatch -- the same cross-check technique the Clean sibling's driver.py uses, deliberately misapplied here.",
    },
    {
        "tool": "StrykerJS", "package": "signalbox", "status": "measured",
        "domain": "A three-phase traffic signal controller whose 3 tests all call their target method but only ever assert.ok(true), never pinning a return value.",
        "invalid_means": "Stryker reports a final mutation score of 5.13 against a break threshold of 100 -- 94.87% of mutants survive or go uncovered.",
        "command": "stryker run",
        "notes": "Every test in this folder exercises its target function but asserts nothing about its behavior, so almost every mutant (AssignmentOperator, ConditionalExpression, and more) survives untouched -- a near-total mutation-testing failure, not a marginal one.",
    },
    {
        "tool": "trivy", "package": "cargodrop", "status": "not_installed",
        "domain": "A cargo-yard loading-dock scheduler carrying a hardcoded API-token-shaped string and a real vulnerable runtime dependency (minimist@0.0.8).",
        "invalid_means": "A real trivy scan would flag the hardcoded secret-shaped string and the known-vulnerable minimist@0.0.8 dependency -- both are present and real, but trivy itself cannot be measured here (see notes).",
        "command": "trivy fs --scanners vuln,secret --exit-code 1 .",
        "notes": "Same egress constraint as the Clean sibling: the trivy binary is a GitHub release asset, blocked by this sandbox's allowlist. Source only, genuinely vulnerable by inspection (confirmed separately via npm audit against the identical minimist@0.0.8 dependency in the npm-audit folder), not measured in this environment.",
    },
]
