#!/usr/bin/env bash
# npm audit + npm ls -- primary tool, branch JS_V21_PARCEL_YARN_MICRO (Node 21).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"

cd "$ROOT"
FINDINGS_EXIT=1
FINDINGS_RC_MAX=1
npm audit --json > reports/npm-audit.json ; npm ls --all --json > reports/npm-ls.json
rc=$?
accept_findings "npm-audit" "$rc" "reports/npm-audit.json"
exit $?
