#!/usr/bin/env bash
# cyclomatic-complexity -- alternative tool, branch JS_V21_VITE_YARN_MICRO (Node 21).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/tools/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "cyclomatic-complexity" "cyclomatic-complexity" "cyclomatic-complexity@1.2.5"

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
cyclomatic-complexity packages
rc=$?
accept_findings "cyclomatic-complexity" "$rc" "reports/cyclomatic-complexity.json"
exit $?
