#!/usr/bin/env bash
# monocart-coverage-reports -- alternative tool, branch JS_V21_WEBPACK_PNPM_MONO (Node 21).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "monocart" "monocart-coverage-reports" "monocart-coverage-reports@2.13.0"

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
node -e "require('monocart-coverage-reports')" && mcr merge coverage -o reports/monocart
rc=$?
accept_findings "monocart" "$rc" "reports/monocart"
exit $?
