#!/usr/bin/env bash
# eslint -- primary tool, branch JS_V16_WEBPACK_YARN_MONO (Node 16).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "eslint" "eslint" "eslint@8.57.1"
require_smoke "eslint" "eslint@8.57.1" node_modules/.bin/eslint --version

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
eslint . -f json -o reports/eslint.json
rc=$?
accept_findings "eslint" "$rc" "reports/eslint.json"
exit $?
