#!/usr/bin/env bash
# eslint-plugin-security -- primary tool, branch JS_V21_ROLLUP_NPM_MICRO (Node 21).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/tools/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "security" "eslint-plugin-security" "eslint-plugin-security@4.0.1"

cd "$ROOT"
FINDINGS_EXIT=1
node_modules/.bin/eslint . --no-eslintrc --rulesdir . --parser-options=ecmaVersion:2022 --rule '{"security/detect-object-injection": "warn"}' -f json -o reports/security.json 2>&1 || true
node_modules/.bin/eslint . --rule '{"security/detect-object-injection": "warn"}' -f json -o reports/security.json
rc=$?
accept_findings "security" "$rc" "reports/security.json"
exit $?
