#!/usr/bin/env bash
# Lizard -- primary tool, branch JS_V16_ROLLUP_NPM_MICRO (Node 16).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_binary "lizard" "lizard"

cd "$ROOT"
FINDINGS_EXIT=1
lizard packages -X --csv
rc=$?
accept_findings "lizard" "$rc" "reports/lizard.csv"
exit $?
