#!/usr/bin/env bash
# knip -- alternative tool, branch JS_V26_TURBOPACK_BUN_MICRO (Node 26).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/tools/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "knip" "knip" "knip@6.36.0"
require_smoke "knip" "knip@6.36.0" node_modules/.bin/knip --version

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
knip --reporter json > reports/knip.json
rc=$?
accept_findings "knip" "$rc" "reports/knip.json"
exit $?
