#!/usr/bin/env bash
# knip -- alternative tool, branch JS_V14_VITE_NPM_MONO (Node 14).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "knip" "knip" "n/a"
require_smoke "knip" "n/a" node_modules/.bin/knip --version

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
knip --reporter json > reports/knip.json
rc=$?
accept_findings "knip" "$rc" "reports/knip.json"
exit $?
