#!/usr/bin/env bash
# Dolos -- alternative tool, branch JS_V21_ESBUILD_YARN_MONO (Node 21).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/tools/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "dolos" "@dodona/dolos" "@dodona/dolos@2.9.3"
require_smoke "dolos" "@dodona/dolos@2.9.3" node_modules/.bin/dolos --version

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
dolos src -f json -o reports/dolos.json
rc=$?
accept_findings "dolos" "$rc" "reports/dolos.json"
exit $?
