#!/usr/bin/env bash
# jscpd -- primary tool, branch JS_V24_ROLLUP_YARN_MICRO (Node 24).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/tools/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "jscpd" "jscpd" "jscpd@5.2.1"
require_smoke "jscpd" "jscpd@5.2.1" node_modules/.bin/jscpd --version

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
jscpd . --config .jscpd.json
rc=$?
accept_findings "jscpd" "$rc" "reports/jscpd-report.json"
exit $?
