#!/usr/bin/env bash
# jscpd -- primary tool, branch JS_V16_TURBOPACK_YARN_MONO (Node 16).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "jscpd" "jscpd" "jscpd@4.3.0"
require_smoke "jscpd" "jscpd@4.3.0" node_modules/.bin/jscpd --version

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
jscpd . --config .jscpd.json
rc=$?
accept_findings "jscpd" "$rc" "reports/jscpd-report.json"
exit $?
