#!/usr/bin/env bash
# gutcheck -- alternative tool, branch JS_V21_PARCEL_NPM_MONO (Node 21).
# Generated by gen_js_corpus.py. Do not hand-edit.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=/dev/null
. "$ROOT/Tool Triggering (Synthetic Data)/_skip.sh"

mkdir -p "$ROOT/reports"
require_require "gutcheck" "gutcheck" "gutcheck@0.10.0"

cd "$ROOT"
FINDINGS_EXIT=1   # non-zero from this tool means 'found something', not 'broke'
gutcheck src
rc=$?
accept_findings "gutcheck" "$rc" "reports/gutcheck.json"
exit $?
